name: hands_on_firebase
description: A app to ask and do favors to/from a friend.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  uuid: 1.0.3
  datetime_picker_formfield: ^0.1.8
  firebase_core: ^0.3.4  # Firebase Core 
  firebase_auth: ^0.8.4+5  # Firebase Auth   
  cloud_firestore: ^0.9.5 # Cloud Firestore
  firebase_storage: ^2.1.0 # Firebase Storage
  image_picker: ^0.6.0+3 # Image picker
  firebase_admob: ^0.8.0 # AdMob
  firebase_ml_vision: ^0.6.0 # ML Vision
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/default_avatar.png
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700
